### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by DanielAndreasen** [smockle/linter-proselint#1]
I installed the package first with `pip`, then this package in atom. I open up a `LaTeX` document, and no errors show up (which seems suspicous.
Thanks for porting to atom :)

**Comment by steelbrain** [comment]
Are you using the default latex grammar package or a third party package?

@smockle This would be as simple as adding `source.latex` to language grammars

**Comment by DanielAndreasen** [comment]
For latex I have the following packages installed: `language-latex`, `latexer`, and the default `language-text`.

**Comment by steelbrain** [comment]
Looks like `language-latex` is using `text.tex.latex` as the grammar scope

**Comment by DanielAndreasen** [comment]
Great I think. Can you maybe walk me through how I get it to work :smile:

**Comment by smockle** [comment]
Thanks for reporting this! I’ll enable the `text.tex.latex` and `source.latex` grammars in the next version. The only example in the `proselint` README used Markdown, but I’d imagine it would work fine with most text formats. I may add a config field for custom grammars.

**Comment by DanielAndreasen** [comment]
Indeed I just opened a Markdown document, and it gave a few errors. But yes, it would be helpful in LaTeX as well.

**Comment by smockle** [comment]
I noticed there are several grammars defined by the language-latex package: https://github.com/area/language-latex/tree/master/grammars. Would adding `text.tex` to the list sufficiently cover all of them, or do I need to add each specifically? (e.g. I’m unclear whether `text.tex` expands to include `text.tex.latex` when listed in a linter plugins `grammarScopes`)

**Comment by steelbrain** [comment]
@smockle I would recommend we use the ones from [`linter-chktex`](https://github.com/nscaife/linter-chktex/blob/83cb101ee1a8cd4d1b3852d750a48be2aa3ef8a7/lib/linter-chktex.coffee#L40)

**Comment by smockle** [comment]
@steelbrain I installed language-latex and downloaded a few sample files from https://www.math.duke.edu/computing/tex/templates.html. Linting works with the `linter-chktex` grammars; thanks for the tip!

@DanielAndreasen Thanks for trying the plugin! I just published version 2, which adds built-in support for LaTeX documents. Please reopen this issue if it doesn’t lint for you, and if possible include a sample document.

**Comment by DanielAndreasen** [comment]
@smockle Thanks for the fix, it's installed and it works. It might be useful to not give warnings/errors inside tex-enviroments as `\begin{table}[htbp!]`. But this might be out of the scope of this plugin.

**Comment by lucascosti** [comment]
I'm facing a similar issue with my `.adoc` documents. Currently using [language-asciidoc](https://atom.io/packages/language-asciidoc), is there any way I can get this linting as well?

**Comment by Arcanemagus** [comment]
@lucascosti Please file a new issue requesting support for that to be added.
