### ISSUE TITLE
Does it support Python 3?

### ISSUE THREAD

**Issue by stared** [smockle/linter-proselint#3]
Command line `proselint` works on my computer (OSX) with Python 3. But when I tried to run it in Atom, I got a red box with:

> Error: Traceback (most recent call last): File "/usr/local/bin/proselint", line 11, in sys.exit(proselint()) File "/usr/local/lib/python3.4/site-packages/click/core.py", line 664, in call return self.main(args, *kwargs) File "/usr/local/lib/python3.4/site-packages/click/core.py", line 621, in main raise RuntimeError('Click will abort further execution ' RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

```Error: Traceback (most recent call last):
  File "/usr/local/bin/proselint", line 11, in <module>
    sys.exit(proselint())
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 621, in main
    raise RuntimeError('Click will abort further execution '
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
    at parameters.exit (/Users/piotrmigdal/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.js:86:25)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Or alternatively, is it possible to set that `linter-proselint` uses Python 2?

**Comment by stared** [comment]
(Even after showing this message apparently it works.)

**Comment by smockle** [comment]
Hi @stared, thanks for reporting this. `proselint` requires [`click`](http://click.pocoo.org/5/), a Python library for creating command line interfaces. According to the documentation, `click` has [issues with Python 3](http://click.pocoo.org/5/python3/#python-3-limitations): 

> If you see something like this error in Python 3:
> ```
> Traceback (most recent call last):
>   ...
> RuntimeError: Click will abort further execution because Python 3 was
>   configured to use ASCII as encoding for the environment. Either switch
>   to Python 2 or consult http://click.pocoo.org/python3/ for
>  mitigation steps.
> ```
> You are dealing with an environment where Python 3 thinks you are restricted to ASCII data. The solution to these problems is different depending on which locale your computer is running in.

One of the workarounds `click` provides is to set a few locale-related environment variables (e.g. `LC_ALL` and `LANG`). My guess is that when `proselint` is run from the command line (i.e. outside of Atom), those variables are being set for you.

I’ll research how other plugins using Python set up their environment in Atom Editor. If the Atom plugin can set the same environment variables, these warnings should go away.

**Comment by Arcanemagus** [comment]
@smockle You are already using the `Helpers.exec()` function, which _should_ be pulling in something like that if it is defined. If you are using virtualenv though @stared then you need to close all instances of Atom and launch from there to get full support. (Some of the other Python based packages have hacks in there for specifying the path based on the current project, but that wouldn't fix this particular problem.)

**Comment by sebastianbarfort** [comment]
I get exactly the same error, but for me `proselint` wont' work:

`[Linter] Error running proselint Error: Traceback (most recent call last):
  File "/usr/local/bin/proselint", line 11, in <module>
    sys.exit(proselint())
  File "/Users/sbarfort/Library/Python/3.6/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sbarfort/Library/Python/3.6/lib/python/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/Users/sbarfort/Library/Python/3.6/lib/python/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.`
